# Generated by Django 5.0.4 on 2024-04-18 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dulces',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='dulces',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='dulces',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dulces',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='saladas',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='saladas',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='saladas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='saladas',
            name='nombre',
        ),
        migrations.AddField(
            model_name='dulces',
            name='receta',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.recetas'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'Receta'), (1, 'Receta Salada'), (2, 'Receta Dulce')], default=0),
        ),
        migrations.AddField(
            model_name='saladas',
            name='receta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.recetas'),
        ),
    ]
