# Generated by Django 5.0.4 on 2024-04-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_dulces_categoria_remove_dulces_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dulces',
            old_name='precio',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='saladas',
            old_name='precio',
            new_name='nombre',
        ),
    ]
