# Generated by Django 5.0.4 on 2024-04-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_precio_dulces_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
        migrations.AlterField(
            model_name='dulces',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saladas',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
