# Generated by Django 5.0.4 on 2024-04-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_recetas_imagen_alter_dulces_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='receta/'),
        ),
    ]
