# Generated by Django 5.0.4 on 2024-04-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_recetas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='categoria',
            field=models.IntegerField(choices=[('recetas', 'recetas'), ('saladas', 'saladas'), ('dulces', 'dulces')], default='recetas'),
        ),
    ]
