# Generated by Django 5.0.4 on 2024-04-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_recetas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='categoria',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
