# Generated by Django 5.0.4 on 2024-04-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_saladas_receta_alter_recetas_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='recetas',
            name='categoria',
            field=models.CharField(choices=[('0', 'Recetas'), ('1', 'Saladas'), ('2', 'Dulces')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.imagen'),
        ),
    ]
