# Generated by Django 5.0.4 on 2024-05-01 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_personajes_remove_recetas_imagen_delete_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('personajes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.personajes')),
            ],
            bases=('bookings.personajes',),
        ),
    ]
