# Generated by Django 5.0.4 on 2024-05-02 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_categoria_alter_personajes_tipo_delete_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fecha',
                'verbose_name_plural': 'Fechas',
            },
        ),
        migrations.RemoveField(
            model_name='personajes',
            name='tipo',
        ),
        migrations.AddField(
            model_name='personajes',
            name='fecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.fecha'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
