# Generated by Django 5.0.4 on 2024-05-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_fecha_remove_personajes_tipo_personajes_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='fecha_creacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personaje_creado', to='bookings.fecha'),
        ),
    ]
