# Generated by Django 5.0.4 on 2024-05-02 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_fecha_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
