# Generated by Django 5.0.4 on 2024-05-02 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_fecha_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='fecha',
        ),
        migrations.AddField(
            model_name='personajes',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
