# Generated by Django 5.0.4 on 2024-05-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_alter_personajes_nombre_alter_personajes_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
