# Generated by Django 5.0.4 on 2024-05-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_alter_fecha_descripcion_alter_personajes_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='serie',
            field=models.CharField(max_length=100),
        ),
    ]
